- id: notify-on-restart
  alias: Notify on restart
  description: ''
  trigger:
  - event: start
    platform: homeassistant
  condition: []
  action:
  - data:
      message: Your Hass.io server has restarted ♡
      title: ToKer Home
    service: notify.mobile_app_ios
- id: auto-theme
  alias: Auto theme
  description: ''
  trigger:
  - event: start
    platform: homeassistant
  condition: []
  action:
  - delay: 00:00:01
  - service: script.google_light_theme
- id: notify-failed-login
  alias: Notify failed login
  description: ''
  trigger:
  - entity_id: persistent_notification.http_login
    platform: state
    to: notifying
  condition: []
  action:
  - data:
      message: '{{ states.persistent_notification.http_login.attributes.message }}'
      title: '{{ states.persistent_notification.http_login.attributes.title }}'
    service: notify.mobile_app_ios
  - delay: '5'
  - data:
      notification_id: http_login
    service: persistent_notification.dismiss
- id: '5'
  alias: 5 - Köket On
  description: ''
  trigger:
  - entity_id: light.koket
    platform: state
    to: 'on'
  condition: []
  action:
  - service: script.koksbordet_on
- id: '6'
  alias: 6 - Köket off
  description: ''
  trigger:
  - entity_id: light.koket
    platform: state
    to: 'off'
  condition: []
  action:
  - service: script.koksbordet_off
- id: toker-alone
  alias: ToKer Alone
  description: ''
  trigger:
  - entity_id: person.kanita
    from: home
    platform: state
  - entity_id: person.tim
    from: home
    platform: state
  condition:
  - condition: and
    conditions:
    - condition: template
      value_template: '{{ (states(''device_tracker.google_maps_106326879474919188136'')
        != ''home'') }}'
    - condition: template
      value_template: '{{ (states(''device_tracker.ios'') != ''home'') }}'
  action:
  - data:
      message: is alone, turning down the lights ♡
      name: ToKer
    service: logbook.log
  - service: script.brightness_low
- id: ios_badrummet
  alias: iOS Event Badrummet
  description: ''
  trigger:
  - event_data:
      actionName: Badrummet
    event_type: ios.action_fired
    platform: event
  condition: []
  action:
  - entity_id: light.badrummet
    service: script.toggle_badrummet
- id: toker-home
  alias: ToKer Home
  description: ''
  trigger:
  - entity_id: person.tim
    platform: state
    to: home
  condition:
  - condition: template
    value_template: '{{ not is_state("person.kanita", "home") }}'
  action:
  - entity_id: script.coming_home
    service: script.turn_on
- id: lightify
  alias: Lightify
  description: Lightify
  trigger:
  - platform: webhook
    webhook_id: lightify
  condition: []
  action:
  - data:
      brightness: 1
    entity_id: light.sanglampa_t
    service: light.turn_on
  - delay: 00:00:01
  - data:
      brightness: 255
      transition: 30
      white_value: 255
    entity_id: light.sanglampa_t
    service: light.turn_on
