homeassistant:
  homeassistant:

####################################################################

default_config:
stream:
shopping_list:
websocket_api:

automation: 
  !include automations.yaml

binary_sensor: 

camera: 
  !include configurations/camera.yaml

cloudflare:
  !include configurations/cloudflare.yaml

discovery: 
#  !include configurations/discovery.yaml
  ignore:
    - igd
    - netgear_router

device_tracker:
#  - !include configurations/google_maps.yaml
  - platform: google_maps
    username: !secret email

fan:
#  - !include configurations/xiaomi.yaml
  - platform: xiaomi_miio
    host: 192.168.10.7
    token: !secret xiaomi_token
    model: zhimi.airpurifier.mc1
    name:  Xiaomi Air Purifier 2S

frontend: 
  themes: !include_dir_merge_named themes/

google_assistant: 
#  !include configurations/google_assistant.yaml
  project_id: toker-home
  service_account: !secret google_assistant
  report_state: true
  secure_devices_pin: "6046"
  exposed_domains:
    - light
    - lock

group: !include groups.yaml

history: 
#  !include configurations/history.yaml
  use_include_order: true
  include:
    domains:
      - lock
      - media_player
      - light
      - person
      - fan
  exclude:
    domains:
      - switch
      - mobile_app
      - camera
      - automation
      - binary_sensor
      - sensor

http: 
  base_url: !secret http_url
  trusted_proxies: 192.168.10.30
  use_x_forwarded_for: true
  login_attempts_threshold: 5


ifttt: 
#  !include configurations/ifttt.yaml
  key: !secret ifttt_key

lock:
#  - !include configurations/lock.yaml
  - platform: template
    name: Glue
    value_template: >-
      {% if is_state('sensor.glue', 'locked') %}
        locked
      {% elif is_state('sensor.glue', 'unlocked') %}
        unlocked
      {% endif %}
    #optimistic: true
    lock:
      service: script.turn_on
      entity_id: script.6
    unlock:
      service: script.turn_on
      entity_id: script.5

logbook: 
#  !include configurations/logbook.yaml
  exclude:
    entities:
      - automation.cloudflare_dns_update
    domains:
      - sun
      - script
      - automation
      - switch
      - mobile_app
      - camera
      - automation
      - sensor
      - binary_sensor
      - input_select
      - device_tracker

logger: 
#  !include configurations/logger.yaml
  default: warning
  logs:
    custom_components.hacs: debug
    homeassistant.components.homekit_controller: debug
    homeassistant.components.python_script: debug
    homeassistant.components.core: debug
    homeassistant.components.camera: debug
    homeassistant.components.stream: debug
    homeassistant.components.info: debug
    homeassistant.components.updater: debug
    homeassistant.components.automation: info
    homeassistant.components.notify: info
    homeassistant.components.recorder: debug
    homeassistant.components.script: error
    homeassistant.components.sensor: error
    homeassistant.components.binary_sensor: info
    homeassistant.components.switch: error
    homeassistant.components.mqtt: error
    homeassistant.components.light: error
    homeassistant.components.google_assistant: critical
    homeassistant.components.shell_command: debug


lovelace:
  mode: yaml

media_player: 
#  - !include configurations/spotify.yaml
  - platform: spotify
    client_id: !secret spotify_client_id
    client_secret: !secret spotify_client_secret

notify: 
#  - !include configurations/notify.yaml
  - platform: html5
    name: Toker
    vapid_pub_key: !secret vapid_pub_key
    vapid_prv_key: !secret vapid_prv_key
    vapid_email: !secret vapid_email

recorder: 
#  !include configurations/recorder.yaml
  purge_keep_days: 3
  purge_interval: 0
  db_url: !secret postgresql_url


script: 
  !include scripts.yaml

#sensor:
  !include configurations/sensor/glue.yaml
  - platform: template
    sensors:
      glue:
        value_template: >-
          {% if is_state("sensor.glue", "locked") %}
            locked
          {% else %}
            unlocked
          {% endif %}
        friendly_name: 'Glue'
scene: 
  !include scenes.yaml

shell_command:
  git_run: '. git.sh'

switch: 
  - !include configurations/switch/broadlink.yaml

telegram_bot: 
#  - !include configurations/telegram.yaml
  - platform: webhooks
    url: !secret http_url
    api_key: !secret telegram_api_key
    parse_mode: html
    allowed_chat_ids:
      - 513520896

tts:
#   - !include configurations/google_tts.yaml
  - platform: google_translate
    cache: true
    cache_dir: /tts
    time_memory: 57600
    base_url: !secret http_url
    service_name: google_say

updater: 
  !include configurations/updater.yaml


### Standard default_config
# automation
# cloud
# config
# frontend
# history
# logbook
# map
# mobile_app
# person
# script
# ssdp
# sun
# system_health
# updater
# zeroconf
###
