homeassistant:

####################################################################

default_config:
stream:
shopping_list:
websocket_api:

automation: 
  !include automations.yaml

binary_sensor: 

camera: 
  !include configurations/camera.yaml

cloudflare:
  !include configurations/cloudflare.yaml

discovery: 
  !include configurations/discovery.yaml

fan:
  - !include configurations/xiaomi.yaml

frontend: 
  themes: !include_dir_merge_named ../themes/

google_assistant: 
  !include configurations/google_assistant.yaml

group: !include groups.yaml

history: 
  !include configurations/history.yaml

http: 
  !include configurations/http.yaml

ifttt: 
  !include configurations/ifttt.yaml

lock:
  - !include configurations/lock.yaml

logbook: 
  !include configurations/logbook.yaml

logger: 
  !include configurations/logger.yaml

lovelace:
  mode: yaml

media_player: 
  - !include configurations/spotify.yaml

notify: 
  - !include configurations/notify.yaml

recorder: 
  !include configurations/recorder.yaml
  
script: 
  !include scripts.yaml

sensor:
  !include configurations/sensor/glue.yaml

scene: 
  !include scenes.yaml

shell_command:
  git_run: '. git.sh'

switch: 
  - !include configurations/switch/broadlink.yaml

telegram_bot: 
  - !include configurations/telegram.yaml

tts:
  - !include configurations/google_tts.yaml

updater: 
  !include configurations/updater.yaml



### Standard default_config
# automation
# cloud
# config
# frontend
# history
# logbook
# map
# mobile_app
# person
# script
# ssdp
# sun
# system_health
# updater
# zeroconf
###
