homeassistant:
  time_zone: Europe/Stockholm
  unit_system: metric

#default_config:
stream:
shopping_list:
#websocket_api:

android_ip_webcam: !include toker/android-ip-webcam.yaml
binary_sensor: !include toker/binary_sensor.yaml
browser_mod: !include toker/browser_mod.yaml
camera: !include toker/camera.yaml
device_tracker: !include toker/device_tracker.yaml
discovery: !include toker/discovery.yaml
fan: !include toker/fan.yaml
google_assistant: !include toker/google_assistant.yaml
group: !include groups.yaml
http: !include toker/http.yaml
ifttt: !include toker/ifttt.yaml
input_select: !include toker/input-select.yaml
lock: !include toker/lock.yaml
logger: !include toker/logger.yaml
lovelace: !include toker/lovelace.yaml
media_player: !include toker/media_player.yaml
notify: !include toker/notify.yaml
recorder: !include toker/recorder.yaml
scene: !include scenes.yaml
sensor: !include toker/sensor.yaml
shell_command: !include toker/shell_command.yaml
spotify: !include toker/spotify.yaml
switch: !include toker/switch.yaml
#telegram_bot: !include toker/telegram.yaml
tts: !include toker/tts.yaml
zone: !include zones.yaml

##################
# Included in with default_config:

# default_config:
automation: !include automations.yaml
# cloud:
config:
frontend: !include toker/frontend.yaml
history: !include toker/history.yaml
logbook: !include toker/logbook.yaml
map:
mobile_app:
person:
script: !include scripts.yaml
ssdp:
# sun:
system_health:
updater: !include toker/updater.yaml
zeroconf:
