custom_header:
  chevrons: false
  compact_mode: true
  editor_warnings: false
  footer_mode: false
  #header_css: 'padding: 5px;'
  #button_text:
  #  options: '{{ hours24LZ }}:{{ minutesLZ }}'
  
  background: var(--app-header-background-color)
  elements_color: var(--app-header-text-color)
  active_tab_color: var(--state-icon-active-color)
  tab_indicator_color: var(--state-icon-active-color)

resources:
  - url: /community_plugin/button-card/button-card.js
    type: module
  - url: /community_plugin/custom-header/custom-header.js
    type: module
  - url: /community_plugin/mini-media-player/mini-media-player-bundle.js
    type: module
  - url: /community_plugin/simple-weather-card/simple-weather-card-bundle.js
    type: module
  - url: /community_plugin/lovelace-card-mod/card-mod.js
    type: module
  - url: /community_plugin/lovelace-card-tools/card-tools.js
    type: module
  - url: /community_plugin/lovelace-fold-entity-row/fold-entity-row.js
    type: module
  - url: /community_plugin/lovelace-layout-card/layout-card.js
    type: module
  - url: /community_plugin/popup-backdrop-filter/popup-backdrop-filter.js
    type: module
  - url: /community_plugin/button-entity-row/button-entity-row.js
    type: module
  - url: /community_plugin/light-entity-card/light-entity-card.js
    type: js

#  - url: /local/community/light-slider-card/light-slider-card.js
#    type: js
#  - url: /community_plugin/circle-sensor-card/circle-sensor-card.js
#    type: module
#  - url: /community_plugin/vertical-stack-in-card/vertical-stack-in-card.js
#    type: js

title: Toker
# Background:
#background: 'center / cover no-repeat url(/local/background3.jpeg) fixed'
views:

##########################################################

  - title: Home
    path: home
    icon: 'mdi:home'
    panel: true
    badges: []
    cards:

##########################################################

      - type: custom:layout-card
        layout: vertical
        cards:

          - !include ui/weather.yaml
          - !include ui/vardagsrummet-player.yaml
          - !include ui/markdown-location.yaml

##########################################################

          - break
          - type: horizontal-stack
            cards:
              - !include ui/vardagsrummet-power.yaml
              - !include ui/vardagsrummet-volume-off.yaml
              - !include ui/vardagsrummet-volume-down.yaml
              - !include ui/vardagsrummet-volume-up.yaml

##########################################################

          - type: horizontal-stack
            cards:

              - !include ui/button-glue.yaml
              - !include ui/button-blank.yaml
              - !include ui/button-ui.yaml
              #- !include ui/button-ios.yaml
              - !include ui/button-dev.yaml

##########################################################

          - type: horizontal-stack
            cards:

              - !include ui/button-hallen.yaml
              - !include ui/button-koket.yaml
              - !include ui/button-vardagsrummet.yaml
              - !include ui/button-sovrummet.yaml

##########################################################

          - type: horizontal-stack
            cards:

              - !include ui/button-koksbordet.yaml
              - !include ui/button-blank.yaml
              - !include ui/button-blank.yaml
              - !include ui/button-blank.yaml

##########################################################

          - break
#          - !include ui/folding-entity.yaml

          - !include ui/folding-temp.yaml

          - break
          - !include ui/button-blank.yaml

##########################################################

  - title: Camera
    path: camera
    icon: 'mdi:camera'
    badges: []
    cards:

##########################################################

      - !include ui/cam-koket.yaml
      - !include ui/cam-sveavagen-norr.yaml
      - !include ui/cam-sveavagen-soder.yaml
      - !include ui/cam-bromma-to.yaml
      - !include ui/cam-bromma-from.yaml
        
##########################################################

  - title: Dev
    path: dev
    icon: 'mdi:dev-to'
    panel: true
    badges: []
    cards: []
