custom_header:
  chevrons: false
  compact_mode: true
  editor_warnings: false
  footer_mode: false
  #header_css: 'padding: 5px;'

resources:
  - type: module
    url: /community_plugin/button-card/button-card.js
  - type: module
    url: /community_plugin/custom-header/custom-header.js
  - type: module
    url: /community_plugin/mini-media-player/mini-media-player-bundle.js
  - type: module
    url: /community_plugin/simple-weather-card/simple-weather-card-bundle.js
  - type: module
    url: /community_plugin/lovelace-card-mod/card-mod.js
  - type: module
    url: /community_plugin/lovelace-card-tools/card-tools.js
  - type: module
    url: /community_plugin/lovelace-fold-entity-row/fold-entity-row.js
  - type: module
    url: /community_plugin/lovelace-layout-card/layout-card.js
  - type: js
    url: /community_plugin/light-slider-card.js
  - type: module
    url: /community_plugin/popup-backdrop-filter.js
  - type: module
    url: /community_plugin/circle-sensor-card/circle-sensor-card.js
  - type: js
    url: /community_plugin/light-entity-card/light-entity-card.js
  - type: js
    url: /community_plugin/vertical-stack-in-card/vertical-stack-in-card.js
  - type: module
    url: /community_plugin/button-entity-row/button-entity-row.js

title: Toker
background: "center / cover no-repeat fixed url('/local/images/background-tiny.jpeg')"
views:

##########################################################

  - title: Home
    path: home
    icon: 'mdi:home'
    panel: true
    badges: []
    cards:

##########################################################

      - type: custom:layout-card
        layout: vertical
        cards:

          - !include ui/weather.yaml

          - !include ui/vardagsrummet-player.yaml

          - !include ui/markdown-location.yaml

##########################################################

          - break
          - type: horizontal-stack
            cards:

              - !include ui/vardagsrummet-power.yaml

              - !include ui/vardagsrummet-volume-off.yaml

              - !include ui/vardagsrummet-volume-down.yaml

              - !include ui/vardagsrummet-volume-up.yaml

##########################################################

          - type: horizontal-stack
            cards:

              - !include ui/glue-lock.yaml

              - type: 'custom:button-card'
                color_type: blank-card

              - type: 'custom:button-card'
                color_type: blank-card

              - type: 'custom:button-card'
                color_type: blank-card

##########################################################

          - type: horizontal-stack
            cards:

              - !include ui/button-hallen.yaml

              - !include ui/button-koket.yaml

              - !include ui/button-vardagsrummet.yaml

              - !include ui/button-sovrummet.yaml

          - break
          - !include ui/folding-entity.yaml

##########################################################

  - title: Camera
    path: camera
    icon: 'mdi:camera'
    badges: []
    cards:

##########################################################

      - !include ui/cam-koket.yaml

      - !include ui/cam-sveavagen-norr.yaml

      - !include ui/cam-sveavagen-soder.yaml

      - !include ui/cam-bromma-to.yaml

      - !include ui/cam-bromma-from.yaml
        
##########################################################

  - title: Dev
    path: dev
    icon: 'mdi:dev-to'
    panel: true
    badges: []
    cards: []
