custom_header:
  chevrons: false
  compact_mode: true
  editor_warnings: false
  footer_mode: false
  
  background: var(--app-header-background-color)
  elements_color: var(--app-header-text-color)
  active_tab_color: var(--state-icon-active-color)
  tab_indicator_color: var(--state-icon-active-color)

resources:
  - url: /community_plugin/button-card/button-card.js
    type: module
  - url: /community_plugin/custom-header/custom-header.js
    type: module
  - url: /community_plugin/mini-media-player/mini-media-player-bundle.js
    type: module
  - url: /community_plugin/simple-weather-card/simple-weather-card-bundle.js
    type: module
  - url: /community_plugin/lovelace-card-mod/card-mod.js
    type: module
  - url: /community_plugin/lovelace-card-tools/card-tools.js
    type: module
  - url: /community_plugin/lovelace-fold-entity-row/fold-entity-row.js
    type: module
  - url: /community_plugin/lovelace-layout-card/layout-card.js
    type: module
  - url: /community_plugin/popup-backdrop-filter/popup-backdrop-filter.js
    type: module
  - url: /community_plugin/light-entity-card/light-entity-card.js
    type: js

#  - url: /local/community/light-slider-card/light-slider-card.js
#    type: js
#  - url: /community_plugin/circle-sensor-card/circle-sensor-card.js
#    type: module
#  - url: /community_plugin/vertical-stack-in-card/vertical-stack-in-card.js
#    type: js

title: Toker
views:

##########################################################

  - !include ui/view-home.yaml

##########################################################

  - !include ui/view-camera.yaml
        
##########################################################

  - !include ui/view-remote.yaml

##########################################################

  - !include ui/view-spotify.yaml

##########################################################

  - !include ui/view-dev.yaml