custom_header:
  chevrons: false
  compact_mode: true
  editor_warnings: false
  footer_mode: false
  
  background: var(--app-header-background-color)
  elements_color: var(--app-header-text-color)
  active_tab_color: var(--state-icon-active-color)
  tab_indicator_color: var(--state-icon-active-color)

title: Toker

resources: !include ui/resources.yaml

#title: Toker
views:

##########################################################

  - !include ui/view-home.yaml
        
##########################################################

  - !include ui/view-remote.yaml

##########################################################

  - !include ui/view-camera.yaml

##########################################################

  - !include ui/view-spotify.yaml

##########################################################

  - !include ui/view-dev.yaml
