custom_header:
  compact_mode: true
#  footer_mode: false
  background: var(--app-header-background-color)
  elements_color: var(--app-header-text-color)
  active_tab_color: var(--state-icon-active-color)
  tab_indicator_color: var(--state-icon-active-color)

resources:
  - url: /hacsfiles/button-card/button-card.js
    type: module
  - url: /hacsfiles/custom-header/custom-header.js
    type: module
  - url: /hacsfiles/mini-media-player/mini-media-player-bundle.js
    type: module
  - url: /hacsfiles/simple-weather-card/simple-weather-card-bundle.js
    type: module
  - url: /hacsfiles/lovelace-card-mod/card-mod.js
    type: module
  - url: /hacsfiles/lovelace-card-tools/card-tools.js
    type: module
  - url: /hacsfiles/lovelace-fold-entity-row/fold-entity-row.js
    type: module
  - url: /hacsfiles/lovelace-layout-card/layout-card.js
    type: module
  - url: /hacsfiles/popup-backdrop-filter/popup-backdrop-filter.js
    type: module
  - url: /hacsfiles/light-entity-card/light-entity-card.js
    type: js

title: Toker
views:

##########################################################

  - !include ui/view-home.yaml
        
##########################################################

  - !include ui/view-remote.yaml

##########################################################

  - !include ui/view-camera.yaml

##########################################################

  - !include ui/view-spotify.yaml

##########################################################

  - !include ui/view-dev.yaml
