#- platform: generic
#  name: Köket
#  still_image_url: !secret Koket_Generic_Image
#  stream_source: !secret Koket_Generic_Stream

#- platform: ffmpeg
#  name: Köket FFmpeg
#  input: !secret Koket_FFmpeg_Stream

- platform: mjpeg
  name: Mot Bromma
  still_image_url: https://api.trafikinfo.trafikverket.se/v1/Images/TrafficFlowCamera_39626739.Jpeg?type=fullsize
  mjpeg_url: https://api.trafikinfo.trafikverket.se/v1/Images/TrafficFlowCamera_39626739.Jpeg?type=fullsize

- platform: mjpeg
  name: Från Bromma
  still_image_url: https://api.trafikinfo.trafikverket.se/v1/Images/TrafficFlowCamera_39626682.Jpeg?type=fullsize
  mjpeg_url: https://api.trafikinfo.trafikverket.se/v1/Images/TrafficFlowCamera_39626682.Jpeg?type=fullsize

- platform: mjpeg
  name: Sveavägen Norr 
  still_image_url: https://api.trafikinfo.trafikverket.se/v1/Images/TrafficFlowCamera_39626726.Jpeg?type=fullsize
  mjpeg_url: https://api.trafikinfo.trafikverket.se/v1/Images/TrafficFlowCamera_39626726.Jpeg?type=fullsize

- platform: mjpeg
  name: Sveavägen Söder
  still_image_url: https://api.trafikinfo.trafikverket.se/v1/Images/TrafficFlowCamera_39626439.Jpeg?type=fullsize
  mjpeg_url: https://api.trafikinfo.trafikverket.se/v1/Images/TrafficFlowCamera_39626439.Jpeg?type=fullsize

- platform: mjpeg
  name: Odengatan Sveavägen
  still_image_url: https://api.trafikinfo.trafikverket.se/v1/Images/TrafficFlowCamera_39626727.Jpeg?type=fullsize
  mjpeg_url: https://api.trafikinfo.trafikverket.se/v1/Images/TrafficFlowCamera_39626727.Jpeg?type=fullsize

- platform: mjpeg
  name: Odengatan mot Valhallavägen
  still_image_url: https://api.trafikinfo.trafikverket.se/v1/Images/TrafficFlowCamera_39626725.Jpeg?type=fullsize
  mjpeg_url: https://api.trafikinfo.trafikverket.se/v1/Images/TrafficFlowCamera_39626725.Jpeg?type=fullsize

#- platform: generic
#  name: Karlberg
#  still_image_url: https://api.trafikinfo.trafikverket.se/v1/Images/TrafficFlowCamera_39626719.Jpeg?type=fullsize

#- platform: generic
#  name: Solnabron
#  still_image_url: https://api.trafikinfo.trafikverket.se/v1/Images/TrafficFlowCamera_39635187.Jpeg?type=fullsize

#- platform: generic
#  name: Norrtull mot E4
#  still_image_url: https://api.trafikinfo.trafikverket.se/v1/Images/TrafficFlowCamera_39626487.Jpeg?type=fullsize

#- platform: generic
#  name: Norrtull Betal
#  still_image_url: https://api.trafikinfo.trafikverket.se/v1/Images/TrafficFlowCamera_39636160.Jpeg?type=fullsize

#- platform: generic
#  name: Haga Södra
#  still_image_url: https://api.trafikinfo.trafikverket.se/v1/Images/TrafficFlowCamera_39635840.Jpeg?type=fullsize

#- platform: generic
#  name: Haga Norra
#  still_image_url: https://api.trafikinfo.trafikverket.se/v1/Images/TrafficFlowCamera_39627009.Jpeg?type=fullsize

#- platform: onvif
#  name: Köket
#  host: 192.168.10.120
#  port: 1200

#- platform: generic
#  name: ULAW
#  still_image_url: http://192.168.10.120:1200/shot.jpg
#  stream_source: rtsp://192.168.10.120:1200/h264_ulaw.sdp