- platform: websocket_api

- platform: google_geocode
  name: Tim
  origin: person.tim
  options: street, city
  display_zone: hide
  api_key: !secret google_geocode_api
  language: sv-SE
  region: SV

- platform: google_geocode
  name: Kanita
  origin: person.kanita
  #origin: device_tracker.google_maps_106326879474919188136
  options: street, city
  display_zone: hide
  api_key: !secret google_geocode_api
  language: sv-SE
  region: SV

- platform: template
  sensors:
    glue:
      value_template: >-
        {% if is_state("sensor.glue", "locked") %}
          locked
        {% else %}
          unlocked
        {% endif %}
      friendly_name: 'Glue'

    hallen_brightness:
      friendly_name: 'Hallen Brightness'
      icon_template: 'mdi:hanger'
      value_template: >-
        {% if is_state('light.hallen', 'on') %} 
          {{ (state_attr('light.hallen', 'brightness') / 2.54) | round }}
        {% elif is_state('light.hallen', 'off') %}
          off
        {% endif %}

    koket_brightness:
      friendly_name: 'Köket Brightness'
      icon_template: 'mdi:food'
      value_template: >-
        {% if is_state('light.koket', 'on') %} 
          {{ (state_attr('light.koket', 'brightness') / 2.54) | round }}
        {% elif is_state('light.koket', 'off') %}
          off
        {% endif %}

    sovrummet_brightness:
      friendly_name: 'Sovrummet Brightness'
      icon_template: 'mdi:hotel'
      value_template: >-
        {% if is_state('light.sovrummet', 'on') %} 
          {{ (state_attr('light.sovrummet', 'brightness') / 2.54) | round }}
        {% elif is_state('light.sovrummet', 'off') %}
          off
        {% endif %}

    badrummet_brightness:
      friendly_name: 'Badrummet Brightness'
      icon_template: 'mdi:toilet'
      value_template: >-
        {% if is_state('light.badrummet', 'on') %} 
          {{ (state_attr('light.badrummet', 'brightness') / 2.54) | round }}
        {% elif is_state('light.badrummet', 'off') %}
          off
        {% endif %}

    vardagsrummet_brightness:
      friendly_name: 'Vardagsrummet Brightness'
      icon_template: 'mdi:youtube-tv'
      value_template: >-
        {% if is_state('light.vardagsrummet', 'on') %} 
          {{ (state_attr('light.vardagsrummet', 'brightness') / 2.54) | round }}
        {% elif is_state('light.vardagsrummet', 'off') %}
          off
        {% endif %}