- platform: websocket_api

- platform: time_date
  display_options:
    ['time', 'date']

- platform: template
  sensors:
    glue:
      value_template: >-
        {% if is_state("sensor.glue", "locked") %}
          locked
        {% else %}
          unlocked
        {% endif %}
      friendly_name: 'Glue'

    vardagsrummet_percent:
      value_template: >-
        {% if is_state('light.vardagsrummet', 'on') %} 
        {{ (state_attr('light.vardagsrummet', 'brightness') / 2.55) | round }}
        {% endif %}
