- platform: websocket_api

- platform: time_date
  display_options:
    ['time', 'date']

- platform: template
  sensors:
    glue:
      value_template: >-
        {% if is_state("sensor.glue", "locked") %}
          locked
        {% else %}
          unlocked
        {% endif %}
      friendly_name: 'Glue'

    hallen_brightness:
      value_template: >-
        {% if is_state('light.hallen', 'on') %} 
          {{ (state_attr('light.hallen', 'brightness') / 2.54) | round }}
        {% elif is_state('light.hallen', 'off') %}
          off
        {% endif %}

    koket_brightness:
      value_template: >-
        {% if is_state('light.koket', 'on') %} 
          {{ (state_attr('light.koket', 'brightness') / 2.54) | round }}
        {% elif is_state('light.koket', 'off') %}
          off
        {% endif %}

    sovrummet_brightness:
      unit_of_measurement: '%'
      value_template: >-
        {% if is_state('light.sovrummet', 'on') %} 
          {{ (state_attr('light.sovrummet', 'brightness') / 2.54) | round }}
        {% elif is_state('light.sovrummet', 'off') %}
          off
        {% endif %}

    badrummet_brightness:
      value_template: >-
        {% if is_state('light.badrummet', 'on') %} 
          {{ (state_attr('light.badrummet', 'brightness') / 2.54) | round }}
        {% elif is_state('light.badrummet', 'off') %}
          off
        {% endif %}

    vardagsrummet_brightness:
      value_template: >-
        {% if is_state('light.vardagsrummet', 'on') %} 
          {{ (state_attr('light.vardagsrummet', 'brightness') / 2.54) | round }}
        {% elif is_state('light.vardagsrummet', 'off') %}
          off
        {% endif %}