#
# Updating version number and creates release.

name: version
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@master
    - name: update version and tag
      uses: anothrNick/github-tag-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        DEFAULT_BUMP: patch

    - name: add latest tag
      uses: EndBug/latest-tag@latest
      with:
        description: Latest released tag or release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
